image:
  name: senseyeinc/python-base:3.6-ffmpeg
  username: $DOCKER_HUB_UNAME
  password: $DOCKER_HUB_PWORD

pipelines:
  default:
    - step:
        services:
            - redis
        script: # Modify the commands below to build your repository
            - export PATH=$PATH:~/.local/bin
            - pip install .[test] --user
            - pytest
            - pip freeze --user > requirements.txt
        artifacts:
            - requirements.txt

    - step:
        name: Fossa integration
        script:
          - curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          # (commit to bitbucket instead of using in pipeline)
          - FOSSA_API_KEY=$FOSSA_KEY fossa analyze -c .fossa.yml
          # report of dependencies
          - FOSSA_API_KEY=$FOSSA_KEY fossa report licenses -c .fossa.yml
          # fossa test: If there are issues, it prnts them on stdout and exits with code 1
          # add next line in when we are ready to block builds if fossa fails
          - FOSSA_API_KEY=$FOSSA_KEY fossa test -c .fossa.yml

definitions:
  services:
    redis:
      image: redis
      memory: 128
